# Generated by Django 5.1.1 on 2024-09-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='posts',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
